#!/bin/bash

killall Xvnc
rm -rf $HOME/.vnc/localhost:1.pid
rm -rf $PREFIX/tmp/.X1-lock
rm -rf $PREFIX/tmp/.X11-unix/X1

vncserver -xstartup ~/.vnc/xstartup -listen tcp :1 -SecurityTypes None 
vncserver -list
