#! /usr/bin/env bash

RED="31"
BOLDRED="\e[1;${RED}m"
ENDCOLOR="\e[0m"

killall Xvnc
rm -rf $HOME/.vnc/localhost:1.pid
rm -rf $PREFIX/tmp/.X1-lock
rm -rf $PREFIX/tmp/.X11-unix/X1

echo -e "${BOLDRED}
All desktop process has been stopped successfully!
${ENDCOLOR}"
